from django.utils.translation import gettext_lazy as _

# Content for the dedicated /features/<slug>/ marketing pages. Each of these
# ships in the product already but previously had no page of its own to rank
# for search or link to from an ad - see the product audit's Part 3 finding.
FEATURE_PAGES = {
    'loyalty-program': {
        'nav_label': _('Loyalty'),
        'icon': 'bi-star',
        'eyebrow': _('Customer Loyalty'),
        'h1': _('Turn one-time visitors into regulars — automatically'),
        'meta_description': _("GetMenuHub's loyalty program tracks visits by phone number and rewards repeat customers — no app to download, no card to lose."),
        'intro': _('Every restaurant loses customers it never sees again — not because the food was wrong, but because nothing brought them back. A loyalty program is the simplest fix, if it does not add friction for anyone.'),
        'problem_title': _('Punch cards get lost. Apps do not get downloaded.'),
        'problem_text': _('The point of a loyalty program is to bring someone back a second time. Most loyalty tools ask the customer to do work first — download an app, create an account, remember a card — and most simply will not. That friction is why so many independent restaurants never bother with loyalty at all.'),
        'benefits': [
            _('Customers earn points automatically, tracked by the phone number they already give you'),
            _('No app, no account, no card to carry or lose'),
            _('See your top customers ranked by points, right from your dashboard'),
            _('Turn it on or off anytime from Settings — no commitment'),
        ],
        'plan_note': _('Included in the Pro and Business plans.'),
    },
    'table-ordering': {
        'nav_label': _('Table Ordering'),
        'icon': 'bi-qr-code-scan',
        'eyebrow': _('Table-Side Ordering'),
        'h1': _('Orders straight from the table — zero commission, every time'),
        'meta_description': _("Customers scan your table's QR code and order directly from their phone. Orders land on your dashboard instantly, with zero commission per order."),
        'intro': _('Every order taken by hand is a trip across the room: notice the table, walk over, write it down, walk it to the kitchen. Table-side ordering removes that walk entirely.'),
        'problem_title': _('Order-taking is the most repetitive part of service'),
        'problem_text': _('It is also the easiest part to hand to the customer. Given a menu on their own phone, most customers are happy to browse, customize, and send their order themselves — especially when it means not waiting to flag someone down.'),
        'benefits': [
            _("Each table or sunbed gets its own QR code, printed with your restaurant's name on it"),
            _('Customers browse, customize with product options, and order without waving anyone down'),
            _('Orders land on your dashboard in real time, with pricing always verified server-side'),
            _('Zero commission per order — unlike third-party delivery apps'),
        ],
        'plan_note': _('Included in the Pro and Business plans.'),
    },
    'promo-codes': {
        'nav_label': _('Promo Codes'),
        'icon': 'bi-tag',
        'eyebrow': _('Promo Codes'),
        'h1': _('Fill a slow night without discounting every night'),
        'meta_description': _('Create a promo code in seconds — percentage off, usage limit, expiry date — and send it only when you actually need the extra tables.'),
        'intro': _('Blanket discounts train customers to expect a lower price permanently. A promo code you control lets you offer one only when it actually helps — a slow Tuesday, a new dish launch, a regular you want to thank.'),
        'problem_title': _('Discounting every night trains customers to wait for one'),
        'problem_text': _('The restaurants that discount well do it selectively, not by default. Without an easy way to create and retire a code, most owners either never discount at all, or fall into discounting constantly out of habit.'),
        'benefits': [
            _('Create a code in seconds — percentage off, usage limit, expiry date'),
            _('Send it only to the customers and nights that need it'),
            _('Customers apply it themselves at checkout — no manual math for your staff'),
            _('Track exactly how many times each code was used'),
        ],
        'plan_note': _('Included in the Pro and Business plans.'),
    },
    'analytics': {
        'nav_label': _('Analytics'),
        'icon': 'bi-graph-up',
        'eyebrow': _('Sales Analytics'),
        'h1': _('Know your best — and worst — selling dish before it costs you'),
        'meta_description': _('See revenue trends and your top-selling products at a glance, so you never over-order or run out of your best dish again.'),
        'intro': _('Every order already tells you something about what to buy, what to feature, and what to quietly drop from the menu. Most restaurants just never get to look at it that way.'),
        'problem_title': _('The data exists. It is just not usable at 11pm after a shift.'),
        'problem_text': _('A spreadsheet nobody updates is not a reporting system. Statistics that update themselves, from orders you are already taking, are the only kind an independent restaurant will actually check.'),
        'benefits': [
            _('See revenue for today, this week, and this month at a glance'),
            _('Spot your top-selling products before you run out of stock'),
            _('Export every order to CSV for your own bookkeeping'),
            _('No spreadsheets to maintain — it updates as orders come in'),
        ],
        'plan_note': _('Included in the Business plan.'),
    },
    'staff-management': {
        'nav_label': _('Staff Management'),
        'icon': 'bi-people',
        'eyebrow': _('Staff Management'),
        'h1': _("See what your team's doing without standing over their shoulder"),
        'meta_description': _('Give each staff member their own login with role-based access, and see exactly who changed what and when.'),
        'intro': _("A shared login means you can never tell who did what. Individual logins with the right access level fix that without anyone feeling watched — the log is just there if you ever need it."),
        'problem_title': _('One shared password is a liability, not a shortcut'),
        'problem_text': _('When everyone uses the same login, a mistake or a missed order has no owner. Separate accounts with clear roles cost nothing to set up and remove the guesswork the next time something goes wrong.'),
        'benefits': [
            _('Give each staff member their own login — Admin or Employee'),
            _('Admins manage the menu and settings; Employees just take and update orders'),
            _('Every status change is logged with who made it and when'),
            _('Remove access instantly the moment someone leaves'),
        ],
        'plan_note': _('Included in the Business plan.'),
    },
    'multi-language-menu': {
        'nav_label': _('Multi-language Menu'),
        'icon': 'bi-translate',
        'eyebrow': _('Multi-language Menu'),
        'h1': _('Serve tourists and locals alike — automatically'),
        'meta_description': _('Add an English name for any dish alongside the original, and GetMenuHub shows the right language to each visitor automatically.'),
        'intro': _('A menu only the regulars can read turns away exactly the customers who are most likely to order something they do not recognize — and ask a server to translate it under pressure.'),
        'problem_title': _('Printing two menus is not a real solution'),
        'problem_text': _('It doubles the work every time a price or dish changes, and it still requires someone to hand the visitor the right one. A menu that adapts itself removes that step entirely.'),
        'benefits': [
            _('Set an English name for any dish alongside its original name'),
            _('The menu shows the right language to each visitor automatically'),
            _('No duplicate menus to keep in sync when something changes'),
            _('Available on every plan, starting from Basic'),
        ],
        'plan_note': _('Included in every plan, starting from Basic.'),
    },
}
