# Generated by Django 4.2.7 on 2026-07-15 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('table_type', models.CharField(blank=True, choices=[('table', 'Τραπέζι'), ('sunbed', 'Ξαπλώστρα')], default='table', max_length=10)),
                ('table_number', models.CharField(blank=True, max_length=10)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_notes', models.TextField(blank=True)),
                ('items', models.JSONField(default=list)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('promo_code', models.CharField(blank=True, max_length=30)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Εκκρεμεί'), ('confirmed', 'Επιβεβαιωμένη'), ('preparing', 'Παρασκευάζεται'), ('ready', 'Έτοιμη'), ('delivered', 'Παραδόθηκε'), ('cancelled', 'Ακυρώθηκε')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Εκκρεμεί'), ('paid', 'Πληρώθηκε'), ('failed', 'Απέτυχε'), ('refunded', 'Επιστροφή')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_id', models.CharField(blank=True, max_length=200)),
                ('loyalty_points_awarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('pending', 'Εκκρεμεί'), ('confirmed', 'Επιβεβαιωμένη'), ('preparing', 'Παρασκευάζεται'), ('ready', 'Έτοιμη'), ('delivered', 'Παραδόθηκε'), ('cancelled', 'Ακυρώθηκε')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Εκκρεμεί'), ('confirmed', 'Επιβεβαιωμένη'), ('preparing', 'Παρασκευάζεται'), ('ready', 'Έτοιμη'), ('delivered', 'Παραδόθηκε'), ('cancelled', 'Ακυρώθηκε')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.order')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('options', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'status'], name='orders_orde_restaur_17016b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', '-created_at'], name='orders_orde_restaur_7d58ee_idx'),
        ),
    ]
