# Generated by Django 4.2.7 on 2026-07-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
