# Generated by Django 4.2.7 on 2026-07-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, help_text='English name (optional) - if left blank, the name above is shown', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='preparation_time',
            field=models.PositiveIntegerField(default=15, help_text='Preparation time in minutes'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited uses', null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='number',
            field=models.CharField(help_text='e.g. 1, 2, Patio A', max_length=20),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='table_type',
            field=models.CharField(choices=[('table', 'Table'), ('sunbed', 'Sunbed')], default='table', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], max_length=20),
        ),
    ]
