# Generated by Django 4.2.7 on 2026-07-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_product_name_en_alter_product_preparation_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoption',
            options={'ordering': ['group_name', 'id']},
        ),
        migrations.AddField(
            model_name='productoption',
            name='group_name',
            field=models.CharField(blank=True, help_text='Optional. Give two or more options the same group name to make them mutually exclusive (e.g. group "Sweetness" with options "Plain", "Medium", "Sweet"). Leave blank for an independent add-on.', max_length=100),
        ),
    ]
